# all hosts have a cli and this role will
# setup the zshell environment including
# multiple applications.
#
# this role is mandatory for
# all other roles.
- hosts: all
  tags:
    - system
  pre_tasks:
    - name: "Checking for secrets.yml."
      local_action: stat path=secrets.yml
      register: secrets_stat
    - name: "Loading passwords and other secrets."
      include_vars:
        file: secrets.yml
      when: secrets_stat.stat.exists == true
  roles:
    - system

- hosts: all
  tags:
    - common
  roles:
    - common

# this role setups the i3 desktop including
# polybar and rofi (these will be build)
- hosts: desktop
  tags:
    - desktop
  roles:
    - desktop
