- name: "Deploying desktop dotfiles for {{ user.name }}"
  block:
    - name: "Copy dotfiles for {{ user.name }}"
      copy:
        src: "dotfiles/"
        dest: "{{ user.home }}/"
        mode: g=-rwx,o=-rwx
        directory_mode: 0700
        force: yes

    - name: "Generate oomox colorscheme"
      template:
        src:  oomox-colors-DieOberflaechengestaltung.j2
        dest: "{{ user.home }}/.config/oomox/colors/DieOberflaechengestaltung"
        mode: 0600

    - name: "Generate ~/.Xresources"
      template:
        src:  Xressources.j2
        dest: "{{ user.home }}/.Xresources"
        mode: 0600

    - name: "Mkdir {{ user.home }}/.config/i3/config"
      file:
        path: "{{ user.home }}/.config/i3"
        state: directory

    - name: "Generate {{ user.home }}/.config/i3/config"
      template:
        src:  i3_conf.j2
        dest: "{{ user.home }}/.config/i3/config"
        mode: 0600

    - name: "Build DieOberflaechengestaltung GTK2/3 themes"
      command: oomox-cli --make-opts all ~/.config/oomox/colors/DieOberflaechengestaltung
      changed_when: False

    - name: "Build DieOberflaechengestaltung icons"
      command: oomox-gnome-colors-icons-cli ~/.config/oomox/colors/DieOberflaechengestaltung
      changed_when: False

    - name: "Generate rofi_media_menu.conf"
      template:
        src:  rofi_media_menu.conf.j2
        dest: "{{ user.home }}/.config/rofi_media_menu.conf"
        mode: 0600

    - name: "Generate {{ user.home }}/bin/polybar-scripts/inbox-imap-shellnetrc.sh"
      template:
        src:  inbox-imap-shellnetrc.sh.j2
        dest: "{{ user.home }}/bin/polybar-scripts/inbox-imap-shellnetrc.sh"
        mode: 0700

    - name: "Setting executable permissions for some dotfiles"
      file:
        state: touch
        path: "~/{{ item }}"
        mode: u+rwx
        modification_time: preserve
        access_time: preserve
      become_user: "{{ user.name }}"
      loop: "{{ desktop__dotfiles_executable }}"

    - name: "Generate {{ user.home }}/.config/polybar/config"
      template:
        src:  polybar/config.j2
        dest: "{{ user.home }}/.config/polybar/config"
        mode: 0600

  become_user: "{{ user.name }}"
