# basic host setup
---
- name: "Generate setxkbmap_script"
  template:
    src:  setxkbmap_script.j2
    dest: "{{ user.home }}/bin/autostart/always/setxkbmap_script"
    mode: 0755
  when: 'ansible_become == True or user.name == ansible_user'
  loop: '{{ users }}'
  loop_control:
    loop_var: user

- name: Setup default x11 packages
  include: default-packages.yml

- name: Setup i3 and needed tools
  tags:
    i3
  include: i3.yml
