# these packages will be installed by default
# on all target hosts
# be aware that most of them are beeing depended on
common__default_packages:
  - apt-file
  - bc
  - curl
  - detox
  - exuberant-ctags
  - figlet
  - net-tools
  - p7zip-full
  - pass
  - powerline
  - pv
  - ranger
  - shellcheck
  - silversearcher-ag
  - sysfsutils
  - tmux
  - unp
  - unzip
  - wget

common__mandatory_packages:
  - vim
  - git
  - grc
  - zsh

# these users will be created
# the users object is not within the system role, since it is
# used in all roles.
users:
  - name: "testus"
    comment: "numero testus"
    home: /home/testus
    group: users
    groups: adm,sudo
    shell: /bin/zsh
    # the usermod parameter is optional.
    # if set to True, the users will not be added or managed by ansible.
    # this is useful, when your user isn't local. eg: ldap/active directory
    # default is False
    usermod: False
    manage_ssh_keys: False

common__dotfiles_executable:
  - bin/serve_via_http.sh
  - bin/ssh_send_terminfo.zsh
  - .config/ranger/scope.sh

env_BROWSER: firefox
env_EDITOR: vim
