# Pull base image.
FROM derbunman/diebenutzerumgebung:stable-staged

ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

ADD build.sh /
ADD install.zsh /
RUN chmod 755 /build.sh && /bin/zsh -c /build.sh

ADD validate.zsh /
ADD validate2.zsh /
#ADD validate.png /
ADD validate.stable.png /validate.png

RUN ls -l / && chmod 755 /validate2.zsh /validate.zsh && /bin/zsh -c /validate.zsh

RUN perceptualdiff -verbose -threshold 25000 /neofetch1.png /validate.png
