# Pull base image.
FROM derbunman/diebenutzerumgebung:testing-staged

ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
    locale-gen
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8


ADD build.sh /
ADD install.zsh /

#CMD "/bin/zsh" "/build.sh"
RUN chmod 755 /build.sh && /bin/zsh -c /build.sh

ADD validate.zsh /
ADD validate2.zsh /
ADD validate.testing.png /validate.png

RUN ls -l / && chmod 755 /validate2.zsh /validate.zsh && /bin/zsh -c /validate.zsh

RUN perceptualdiff -verbose -threshold 25000 /neofetch1.png /validate.png
