# basic host setup
---
- name: "Setup apt and upgrade"
  block:
    - name: Install aptitude, figlet and zsh using apt
      apt:
        name:
          - aptitude
          # figlet is needed for the motd task
          - figlet
          # zsh is needed for the users task
          - zsh
        state: latest
        update_cache: yes
        force_apt_get: yes
        autoclean: yes
        autoremove: yes
      tags:
        - upgrade

    - name: Upgrade system using apt
      apt:
        update_cache: no
        upgrade: full
      tags:
        - upgrade

    - name: "Check that /etc/ssh/sshd_config exists"
      stat:
        path: /etc/ssh/sshd_config
      register: stat_result

    - name: "Disallow root SSH access"
      lineinfile:
        dest=/etc/ssh/sshd_config
        regexp="^PermitRootLogin"
        line="PermitRootLogin no"
        state=present
      notify: restart_ssh
      when: stat_result.stat.exists == True

    - name: "Setup motd"
      import_tasks: motd.yml

  when: 'ansible_become == True'

  # Create/Modify users
- name: "Setup users"
  import_tasks: users.yml

- name: Making the users a fact
  set_fact: users={{ users }}
