desktop__default_packages:
  - arandr
  - copyq
  - feh
  - mpv
  - pavucontrol
  - udiskie
  - vlc
  - xscreensaver
  - xscreensaver-data-extra
  - xscreensaver-gl
  - xscreensaver-gl-extra
  - xscreensaver-screensaver-bsod
  - xscreensaver-screensaver-webcollage
  - zathura
  - zathura-cb
  - zathura-djvu
  - zathura-pdf-poppler
  - zathura-ps

desktop__mandatory_packages:
  - aosd-cat
  - compton
  - dunst
  - ffmpeg
  - fonts-roboto
  - fonts-roboto-hinted
  - i3
  - libnotify-bin
  - rxvt-unicode-256color
  - slop
  - ssh-askpass
  - vim-gtk3
  - x11-xserver-utils
  - xbindkeys
  - xbindkeys-config
  - xclip
  - xdg-utils
  - xdotool
  - bspwm
  - sxhkd

colors:
  yellow1: dea65f
  yellow2: f0c674
  red1: a54242
  red2: cc6666
  magenta1: 85678f
  magenta2: b294bb
  blue1: 8abeb7
  blue2: 417cae
  cyan1: 5e8d87
  cyan2: 8abeb7
  green1: 8c9440
  green2: b5bd68
  black1: 181818
  black2: 484848
  white1: e5e5e5
  white2: d5d5d5
  foreground: d5d5d5
  background: 282828
  cursor: d5d5d5
  highlight: 1e3d37
  border: 8abeb7

# the user/pw for Streamable should be added to secrets.yml
rofi_media_menu:
  user: False
  password: False
  ffmpeg_pidfile: /tmp/rofimedia.ffmpeg.pid
  video_path: $HOME/Videos
  video_ext: mp4

desktop__dotfiles_executable:
  - bin/autostart/always/applets.sh
  - bin/autostart/always/udiskie.zsh
  - bin/autostart/always/wallpaper.sh
  - bin/autostart/always/xrdb_reload.sh
  - bin/autostart/i3-scratchpad-vim.zsh
  - bin/bosd_cat
  - bin/compton-invert
  - bin/i3-applet-wrapper
  - bin/i3-autostart.zsh
  - bin/i3keys
  - bin/i3subscribe
  - bin/layout_manager.sh
  - bin/polybar-scripts/polybar_wrapper.sh
  - bin/polybar-scripts/system-cpu-frequency.sh
  - bin/polybar-scripts/system-cpu-loadavg.sh
  - bin/rofi_media_menu.zsh
  - bin/rofi_startmenu.zsh
  - bin/screenshot
  - bin/tint_screen.zsh
  - bin/xkeys.zsh
  - bin/bsp_scratch.zsh
  - bin/bspwm_rules.zsh
  - .config/ranger/scope.sh

polybar__email_indicator_url: "undefined"
polybar__modules_left: "startmenu xwindow"
polybar__modules_center: ""
polybar__modules_right: "docker email eth wlan memory cpu system-cpu-frequency temperature system-cpu-loadavg filesystem battery xkeyboard pulseaudio date powermenu"

polybar__wifi_interface: "wlan0"
polybar__eth_interface: "eth0"

polybar__temperature_thermal_zone: 0

polybar__battery_adapter: "AC"
polybar__battery_device: "BAT0"
polybar__battery_full_at: 95

polybar__additional_content: ""

wallpaper_command: "feh --bg-center ~/.wallpapers/DieBenutzerumgebung_logo.png --image-bg '#484848'"
