default_packages:
  - aosd-cat
  - arandr
  - compton
  - copyq
  - dunst
  - feh
  - ffmpeg
  - fonts-roboto
  - fonts-roboto-hinted
  - i3
  - libnotify-bin
  - lxappearance
  - mpv
  - pavucontrol
  - slop
  - udiskie
  - vlc
  - x11-xserver-utils
  - xbindkeys
  - xbindkeys-config
  - xclip
  - xclip
  - xdg-utils
  - xdotool
  - xscreensaver
  - xscreensaver-data-extra
  - xscreensaver-gl
  - xscreensaver-gl-extra
  - xscreensaver-screensaver-bsod
  - xscreensaver-screensaver-webcollage
  - zathura
  - zathura-cb
  - zathura-djvu
  - zathura-pdf-poppler
  - zathura-ps
