desktop__default_packages:
  - arandr
  - copyq
  - feh
  - mpv
  - pavucontrol
  - udiskie
  - vlc
  - xscreensaver
  - xscreensaver-data-extra
  - xscreensaver-gl
  - xscreensaver-gl-extra
  - xscreensaver-screensaver-bsod
  - xscreensaver-screensaver-webcollage
  - zathura
  - zathura-cb
  - zathura-djvu
  - zathura-pdf-poppler
  - zathura-ps

desktop__mandatory_packages:
  - aosd-cat
  - compton
  - dunst
  - ffmpeg
  - fonts-roboto
  - fonts-roboto-hinted
  - i3
  - libnotify-bin
  - rxvt-unicode-256color
  - slop
  - ssh-askpass
  - vim-gtk3
  - x11-xserver-utils
  - xbindkeys
  - xbindkeys-config
  - xclip
  - xdg-utils
  - xdotool


# the user/pw for Streamable should be added to secrets.yml
rofi_media_menu:
    user: False
    password: False
    ffmpeg_pidfile: /tmp/rofimedia.ffmpeg.pid
    video_path: $HOME/Videos
    video_ext: mp4
