#
# this file is sourced by ~/.xprofile
#
skip_global_compinit=1

export __GL_SYNC_DISPLAY_DEVICE=DP-4
export __VDPAU_NVIDIA_SYNC_DISPLAY_DEVICE=DP-4

export PATH="$HOME/bin:$HOME/.local/bin:/usr/lib/ccache:$PATH:/usr/sbin:/sbin"

export BROWSER="firefox"

export DOTFILES=~/.repos/dotfiles

export LANGUAGE=en_US.UTF-8
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
