---
- name: "Register ~/.zshrc.zgen stat for {{ user.name }}"
  stat:
    path: "{{ user.home }}/.zshrc.zgen"
  register: zgen_stat

- name: "Copy ~/.zshrc.zgen for {{ user.name }}"
  copy:
    src: "dotfiles/.zshrc.zgen"
    dest: "{{ user.home }}/.zshrc.zgen"
    owner: "{{ user.name }}"
    mode: 0600
  register: zgen_copy

- name: "Copy dotfiles for {{ user.name }}"
  copy:
    src: "dotfiles/"
    dest: "{{ user.home }}/"
    mode: g=-rwx,o=-rwx
    directory_mode: 0700
    force: yes
  become_user: "{{ user.name }}"

- name: "Remove ~/.zgen directory because the plugins have changed for {{ user.name }}"
  file:
    path: "{{ user.home }}/.zgen"
    state: absent
  when: "zgen_stat.stat.exists == false or zgen_copy.checksum != zgen_stat.stat.checksum"

- name: "Install zgen packages for {{ user.name }}"
  command: "zsh ~/.zshrc"
  become_user: "{{ user.name }}"
  when: "zgen_stat.stat.exists == false or zgen_copy.checksum != zgen_stat.stat.checksum"

- name: "Update zgen packages for {{ user.name }}"
  command: "zsh -c 'umask 22; source ~/.zshrc; zgen update'"
  become_user: "{{ user.name }}"
  when: "zgen_stat.stat.exists == true and zgen_copy.checksum == zgen_stat.stat.checksum"

- name: "Install VIM Plugins for {{ user.name }}"
  command: "{{ item }}"
  become_user: "{{ user.name }}"
  loop:
    - vim -X +PlugClean! +qall -u ~/.vim/vimrc_plug.vim
    - vim -X +PlugInstall! +qall -u ~/.vim/vimrc_plug.vim
    - vim -X +PlugUpdate! +qall -u ~/.vim/vimrc_plug.vim
  changed_when: false
