---
- name: "Register ~/.zshrc.zgen stat for {{ user.name }}"
  stat:
    path: "{{ user.home }}/.zshrc.zgen"
  register: zgen_stat

- name: "Copy ~/.zshrc.zgen for {{ user.name }}"
  copy:
    src: "dotfiles/.zshrc.zgen"
    dest: "{{ user.home }}/.zshrc.zgen"
    owner: "{{ user.name }}"
    mode: '644'
  register: zgen_copy

- name: "Copy dotfiles for {{ user.name }}"
  copy:
    src: "dotfiles/"
    dest: "{{ user.home }}/"
  become_user: "{{ user.name }}"

- name: "Generate rofi_media_menu.conf"
  template:
    src:  rofi_media_menu.conf.j2
    dest: "{{ item.home }}/.config/rofi_media_menu.conf"
    mode: 0755
  become_user: "{{ item.name }}"
  loop: '{{ users }}'

- name: "Remove ~/.zgen directory because the plugins have changed for {{ user.name }}"
  file:
    path: "{{ user.home }}/.zgen"
    state: absent
  when: "zgen_stat.stat.exists == false or zgen_copy.checksum != zgen_stat.stat.checksum"

- name: "Install zgen packages for {{ user.name }}"
  command: "zsh ~/.zshrc"
  become_user: "{{ user.name }}"
  when: "zgen_stat.stat.exists == false or zgen_copy.checksum != zgen_stat.stat.checksum"

- name: "Update zgen packages for {{ user.name }}"
  command: "zsh -c 'source ~/.zshrc; zgen update'"
  become_user: "{{ user.name }}"
  when: "zgen_stat.stat.exists == true and zgen_copy.checksum == zgen_stat.stat.checksum"

- name: "Install VIM Plugins for {{ user.name }}"
  command: "{{ item }}"
  become_user: "{{ user.name }}"
  loop:
    - vim -X +PlugClean! +qall -u ~/.vim/vimrc_plug.vim
    - vim -X +PlugInstall! +qall -u ~/.vim/vimrc_plug.vim
    - vim -X +PlugUpdate! +qall -u ~/.vim/vimrc_plug.vim
  changed_when: false

- name: "Cloning DieOberflaechengestaltung theme and icons for {{ user.name }}"
  git:
    repo: https://github.com/DerBunman/DieOberflaechengestaltung
    dest: "{{ user.home }}/.local/share/DieBenutzerumgebung/DieOberflaechengestaltung"
    update: yes
    clone: yes
    force: yes
  become_user: "{{ user.name }}"
  changed_when: false
  when: "'desktop' in group_names and 'root' != user.name"

- name: "Create a symbolic link for {{ user.name }}"
  become_user: "{{ user.name }}"
  changed_when: false
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ user.name }}"
    state: link
    force: yes
  loop:
    - { dest: ~/.icons, src: ~/.local/share/DieBenutzerumgebung/DieOberflaechengestaltung/icons }
    - { dest: ~/.themes/oomox-DieOberflaechengestaltung, src: ~/.local/share/DieBenutzerumgebung/DieOberflaechengestaltung/themes/oomox-DieOberflaechengestaltung }
  when: "'desktop' in group_names and 'root' != user.name"
