# basic host setup
---
# install all packages needed for the shell
- name: "Setup shell packages"
  include: packages.yml

# Create/Modify users
- name: "Setup users"
  include_tasks: users.yml
  loop: '{{ users }}'
  loop_control:
    loop_var: user

- include_tasks: dotfiles.yml
  # only include the dotfiles for the ansible_user, when
  # ansible_become is not True
  when: 'ansible_become == True or user.name == ansible_user'
  loop: '{{ users }}'
  loop_control:
    loop_var: user
