# basic host setup
---
- name: "Adding/Modifying users."
  block:
    - name: "Add the real users"
      user:
        home: '{{ user.home }}'
        name: '{{ user.name }}'
        comment: '{{ user.comment | default("") }}'
        group: '{{ user.group }}'
        groups: '{{ user.groups | default("") }}'
        shell: '{{ user.shell }}'
        # update_password: on_create
        # password: "{{ lookup('password', '/tmp/passwordfile.{{ user.name }} chars=ascii_letters,digits,hexdigits,punctuation') }}"
        append: yes
      when: 'user.usermod is defined and user.usermod == True'
  when: 'ansible_become == True'

- name: "Add the users authorized_keys"
  authorized_key:
    state: present
    user: '{{ user.name }}'
    key: "{{ user.ssh_keys }}"
  when: 'user.ssh_keys is defined and user.ssh_keys != False'
