# these users will be created
users:
  - name: "testus"
    comment: "numero testus"
    home: /home/testus
    group: users
    groups: adm,sudo
    shell: /bin/zsh
    # the no_usermod parameter is optional.
    # if set to True, the users will not be added or managed by ansible.
    # this is useful, when your user isn't local. eg: ldap/active directory
    no_usermod: False
