# =====================================
# << THIS FILE IS MANAGED BY ANSIBLE >>
# =====================================
#
# DO NOT EDIT THIS FILE - CHANGES WILL BE OVERWRITTEN
# INSTEAD CHANGE THIS FILE IN THE ANSIBLE REPOSITORY.

#
# this file is sourced by ~/.xprofile
#
skip_global_compinit=1


# needed for gpg-agent. (man gpg-agent)
export GPG_TTY=$(tty)

export __GL_SYNC_DISPLAY_DEVICE=DP-4
export __VDPAU_NVIDIA_SYNC_DISPLAY_DEVICE=DP-4

export PATH="$HOME/bin:$HOME/.local/bin:$HOME/go/bin:/usr/lib/ccache:$PATH:/usr/sbin:/sbin"

export BROWSER="firefox"
export EDITOR="vim"

export XDG_CONFIG_HOME=~/.config/

export DOTFILES=~/.repos/dotfiles

export LANGUAGE=en_US.UTF-8
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

export LEXICON_HETZNER_AUTH_USERNAME="lw200552@googlemail.com"
export LEXICON_HETZNER_AUTH_PASSWORD="L94fVz8BnYqmxn"
export LEXICON_HETZNER_AUTH_ACCOUNT="robot"

